services:
  database:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=telecom
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=telecom
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: telecom-api
    ports:
      - '5000:5000'
    depends_on:
      - database
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URI=mongodb://telecom:password@database:27017/telecom?authSource=admin

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: telecom-web
    ports:
      - '3000:3000'
    depends_on:
      - api
    environment:
      - PORT=3000
      - API_URL=http://localhost:5000

volumes:
  mongodb_data:
    driver: local
